blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/dcsil/the-painters-product/discussions
    about: Questions and ideas that don't fit a bug report or feature suggestion
